#!/usr/bin/env python
# -*- coding:utf-8 -*-
import requests, json, os
url_detail = 'https://nowapi.navoinfo.cn/get_course_details'
url_list = 'https://nowapi.navoinfo.cn/get_sections_list_20191230'
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36'
}
for i in range(0, 1500):
    params = {
        'courseId': i,
    }
    print(i, '<----------------------------------------------------------------------------')
    try:
        response = requests.get(url=url_detail, headers=headers, params=params, verify=False)
        page_text = json.loads(response.text)
        title = page_text['result']['course_info']['title']
        path = r'D:\now冥想\{}'.format(title)
        if not os.path.exists(path):
            os.mkdir(path)

        response = requests.get(url=url_list, headers=headers, params=params, verify=False).text
        page_text = json.loads(response)
        dic = {}
        res_list = page_text['result']

        for i in res_list:
            res_dic = i['group_item']
            for m in res_dic:
                if m['language'] == 'cn':
                    dic[m['title']] = m['url']

        num = 1
        for name, url in dic.items():
            response = requests.get(url=url, headers=headers, verify=False).content
            with open('{}\{}.{}.mp3'.format(path, num, name, ), 'wb')as f:
                f.write(response)
                print('{}\{}.{}.mp3'.format(path, num, name, ), '----->OK')
            num += 1

    except Exception:
        pass
